config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  post 'persons/:id' => 'persons#create'
  resources :users
  resources :reminders
  resources :sessions
  resources :persons
  delete '/logout' => 'sessions#destroy'
  get 'amazon_api' => 'reminders#amazon_api', as: :amazon_api
  get 'persons/:id/amazon_api' => 'reminders#amazon_api', as: :amazon_api_person
  get '/auth/:provider/callback' => 'sessions#create'
end

app/models/interest.rb
class Interest < ActiveRecord::Base
	# validates :name, presence: true 

	has_many :person_interests
	has_many :people, through: :person_interests
end

app/models/person.rb
class Person < ActiveRecord::Base
	validates :name, presence: true 
	has_many :person_interests
	has_many :interests, through: :person_interests, dependent: :destroy
	has_many :reminders, dependent: :destroy
end

app/models/person_interest.rb
class PersonInterest < ActiveRecord::Base
  belongs_to :person
  belongs_to :interest
end

app/models/reminder.rb
class Reminder < ActiveRecord::Base
	validates :when, presence: true

  belongs_to :user
  belongs_to :person
  belongs_to :reminder_type
end

app/models/reminder_type.rb
class ReminderType < ActiveRecord::Base
	validates :event, presence: true 
	has_many :reminders
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :reminders
	class << self
		def from_omniauth auth_hash
			user = find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider']) do |u|
				u.name = auth_hash['info']['name']
				u.image_url = auth_hash['info']['image']
				u.email = auth_hash['info']['email']
			end
		end
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  def logged_in?
    unless current_user
      redirect_to root_path
    end
  end

  helper_method :current_user
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  before_action :find_person, only:[:show, :create,:update]
  def index
    @persons = Person.all
    @reminders = Reminder.all
  end

  def show
    @interest = Interest.new
    @keyword = params[:search]
		@type = params[:type]
    @page = params[:page]
		@category = [
			'All', 'DVD', 'Electronics', 'Toys', 'VideoGames', 'PCHardware', 'Tools', 'SportingGoods', 'Books', 'Software', 'Kitchen', 'Apparel','Music','Video'
		]

    request = Vacuum.new('US')
    request.configure(
      aws_access_key_id: ENV['aws_access_key_id'],
      aws_secret_access_key: ENV['aws_secret_access_key'],
      associate_tag: ENV['associate_tag']
      )

    params = {
        'SearchIndex' => @type,
        'Keywords'=> @keyword,
        'ItemPage' => @page,
        'ResponseGroup' => "ItemAttributes,Images,Offers"
      }

      ## DEFINES THE REQUEST RETURN
      raw_products = request.item_search(query: params)
      hashed_products = raw_products.to_h
      ## PUTS SPECIFICS OF HASHED SEARCH RESPONSE INTO AN ARRAY
      @products = hashed_products['ItemSearchResponse']['Items']['Item']
  end

  def update
    @interest = Interest.find_or_create_by(interest_params)
    @person.interests << @interest
    if @interest.save
      redirect_to person_path(@person.id, search:@interest.name,type:'All')
    end
  end

  def new
  end

  def edit
  end

private
  def interest_params
    params.require(:interest).permit(:name)
  end
  def find_person
    @person = Person.find(params[:id])
  end
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController

	before_action :find_reminder, only:[:show,:edit,:update,:destroy]
	before_action :logged_in?, only:[:index,:edit,:new,:destroy]

  def index
  	@reminders = Reminder.order(:when)
		@reminder = Reminder.new
		@person = Person.new
		@reminder_type = ReminderType.new
  end

  def show
  end

  def new
  end

  def create
  	@reminder = Reminder.new(reminder_params)
		@person = Person.find_or_create_by(name: params[:person][:name])

		@reminder_type = ReminderType.find_or_create_by(event:params[:reminder_type][:event])

		@person.reminders << @reminder
		@reminder_type.reminders << @reminder
  	@reminder.user_id = current_user.id
		# sent the sent email/text attribute to false before saving
		@reminder.sent = false
  	if @reminder.save && @person.save && @reminder_type.save
  		redirect_to person_path(@person.id)
  	else
			render :new
  	end
  end

  def edit
	  #code
	end

	def destroy
	  if @reminder.destroy
	  	redirect_to reminders_path
	  end
	end

  def etsy

  end

	def amazon_api
		# All—Searches through all search indices. Only five pages of items can be returned where each page contains up to five items
		#
		# Blended—Combines the following search indices: DVD, Electronics, Toys, VideoGames, PCHardware, Tools, SportingGoods, Books, Software, Music, GourmetFood, Kitchen, and Apparel search indices
		#
		# Music—Combines Classical, DigitalMusic, and MusicTracks search indices
		#
		# Video—Combines DVD and VHS search indices

    @keyword = params[:search]
		@type = params[:type]
		@category = [
			['All'], ['DVD'], ['Electronics'], ['Toys'], ['VideoGames'], ['PCHardware'], ['Tools'], ['SportingGoods'], ['Books'], ['Software'], ['Music'], ['GourmetFood'], ['Kitchen'], ['Apparel'],['Music'],['Video']
		]

    request = Vacuum.new('US')
    request.configure(
      aws_access_key_id: ENV['aws_access_key_id'],
      aws_secret_access_key: ENV['aws_secret_access_key'],
      associate_tag: ENV['associate_tag']
      )

    params = {
        'SearchIndex' => @type,
        'Keywords'=> @keyword,
        'ResponseGroup' => "ItemAttributes,Images,Offers"
      }

      ## DEFINES THE REQUEST RETURN
      raw_products = request.item_search(query: params)
      hashed_products = raw_products.to_h
      ## PUTS SPECIFICS OF HASHED SEARCH RESPONSE INTO AN ARRAY
      @products = hashed_products['ItemSearchResponse']['Items']['Item']
  end

private
	def reminder_params
		params.require(:reminder).permit(:when, :send_text, :send_email, :person_id)
	end
	def find_reminder
		@reminder = Reminder.find(params[:id])
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.from_omniauth(request.env['omniauth.auth'])
    session[:user_id] = @user.id
    flash[:success] = "Welcome, #{@user.name}!"
    @user.save
    if @user.email
      UserMailer.welcome(@user).deliver 
    end
    redirect_to reminders_path
  end
  def destroy
    if current_user
      session.delete(:user_id)
    end
    flash[:notice] = "See you!"
    redirect_to root_path
  end

private

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only:[:show,:edit,:destroy,:update]
  before_action :logged_in?, only:[:show,:edit,:update,:destroy]
  def index
    @users = User.all
  end

  def show
  end

  def new
  end

  def edit

  end

  def update
    if @user.update(user_params)
      redirect_to reminders_path
    else
      render :edit
    end
  end

private
  def user_params
    params.require(:user).permit(:name,:email,:phone)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Giftdr2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-custom snavbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Giftdr', root_path, class: 'navbar-brand' %>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <% if current_user %>
          <ul class="nav navbar-nav">
            <li><%= link_to current_user.name, reminders_path %></li>
            <li><%= link_to 'Settings', user_path(current_user.id) %></li>
            <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav pull-right">
            <li><%= link_to 'Facebook', '/auth/facebook' %></li>
          </ul>
        <% end %>
      </div>
    </div>
  </nav>
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: "name alert alert-success container" %>
<% end %>
<%= yield %>
</body>
</html>

app/views/pages/home.html.erb
<header>
  <div class="header-content">
      <div class="header-content-inner">
          <h1>Never forget another important event!</h1>
           <hr class="primary">
          <p>Set Reminder and find useful gift suggestion!</p>
      </div>
      <a href="#services" class="btn btn-primary btn-lg page-scroll">Find Out More</a>
  </div>
</header>
<section id="services">
  <div class="container">
    <div class="row">
        <div class="col-lg-12 text-center">
            <h2 class="section-heading">As easy as 1 - 2 - 3!</h2>
        </div>
    </div>
    <div class="row text-center service-wrapper">
      <div class="service-box col-lg-4 text-center">
          <i class="fa fa-4x fa-bell-o wow bounceIn text-primary"></i>
          <h3>Set a reminder</h3>
          <p class="text-muted">Set a reminder of important events</p>
      </div>
      <div class="service-box col-lg-4 text-center">
          <i class="fa fa-4x fa-paper-plane wow bounceIn text-primary" data-wow-delay=".1s"></i>
          <h3>Receive a text or email</h3>
          <p class="text-muted">Reminder come with gifts suggestion!</p>
      </div>
      <div class="service-box col-lg-4 text-center">
          <i class="fa fa-4x fa-cart-plus wow bounceIn text-primary" data-wow-delay=".2s"></i>
          <h3>Purchase a gift</h3>
          <p class="text-muted">Through our affiliates Amazon!</p>
      </div>
        <a href="#team" class="btn btn-primary btn-lg page-scroll what">Meet the Team!</a>
    </div>
  </div>
</section>

<!-- Team Section -->
    <section id="team" class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Our Giftdr Team!</h2>
                    <h3 class="section-subheading text-muted">Who is behind this amazing app you might ask?</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <div class="team-member">
                        <img src="https://avatars0.githubusercontent.com/u/8016648?v=3&s=400" class="img-responsive img-circle resize" alt="">
                        <h4>Samuel Chun</h4>
                        <p class="text-muted">Project Manager</p>
                        <ul class="list-inline social-buttons">
                            <li><a href="https://github.com/Ephapox"><i class="fa fa-github"></i></a>
                            </li>
                            <li><a href="https://www.facebook.com/ephapox"><i class="fa fa-facebook"></i></a>
                            </li>
                            <li><a href="https://www.linkedin.com/profile/view?id=133133083&authType=NAME_SEARCH&authToken=EcGs&locale=en_US&srchid=241785141435534531268&srchindex=1&srchtotal=82&trk=vsrp_people_res_name&trkInfo=VSRPsearchId%3A241785141435534531268%2CVSRPtargetId%3A133133083%2CVSRPcmpt%3Aprimary%2CVSRPnm%3Atrue"><i class="fa fa-linkedin"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="team-member">
                        <img src="https://avatars2.githubusercontent.com/u/11948593?v=3&s=400" class="img-responsive img-circle" alt="">
                        <h4>Nicholas Dalke</h4>
                        <p class="text-muted">Lead Tester</p>
                        <ul class="list-inline social-buttons">
                            <li><a href="https://github.com/NickDalke"><i class="fa fa-github"></i></a>
                            </li>
                            <li><a href="https://www.facebook.com/nick.dalke?fref=ts"><i class="fa fa-facebook"></i></a>
                            </li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="team-member">
                        <img src="https://avatars3.githubusercontent.com/u/11904900?v=3&s=400" class="img-responsive img-circle" alt="">
                        <h4>Max Tran</h4>
                        <p class="text-muted">API Specialist</p>
                        <ul class="list-inline social-buttons">
                            <li><a href="https://github.com/maxonrails"><i class="fa fa-github"></i></a>
                            </li>
                            <li><a href="https://www.facebook.com/profile.php?id=100009677800366"><i class="fa fa-facebook"></i></a>
                            </li>
                            <li><a href="https://www.linkedin.com/profile/view?id=24178514&trk=nav_responsive_tab_profile_pic"><i class="fa fa-linkedin"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>

app/views/persons/_interest.html.erb
<div class="row add-interest container">
<%= form_for @person do |p| %>
  <%= fields_for @interest do |i| %>
  <div class="form-group">
    <%= i.text_field :name, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= i.submit 'Add Interest', class:'btn btn-primary' %>
  </div>
  <% end %>
<% end %>
</div>

<div class='dropdown-wrapper row'>
  <div class="dropdown dropdown-search">
    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      <h3>Interest: <%= params[:search].to_s.capitalize %></h3>
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
      <% @person.interests.each do |interest| %>
      <li><%= link_to interest.name.capitalize, person_path(search:interest.name, type:params[:type] || "All", page:1) %></li>
      <% end %>
    </ul>
  </div>
  <div class="dropdown dropdown-type">
    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      <h3>Category: <%= params[:type].to_s %></h3>
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
      <% @category.each do |c| %>
      <li><%= link_to c, person_path(search:params[:search], type:c, page:1), class:"" %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/persons/_pagination.html.erb
<% if params[:search] && params[:type] %>
<nav class="text-center">
  <ul class="pagination">
    <li>
      <% if params[:page].to_i == 1 %>
        <%= link_to '<', person_path(@person.id, search:params[:search],type:params[:type],page:1) %>
      <% else %>
        <%= link_to '<', person_path(@person.id, search:params[:search],type:params[:type],page:params[:page].to_i - 1) %>
      <% end %>
    </li>
    <% (1..5).each do |page| %>
      <% if params[:page].to_i == page.to_i %>
      <li class="active"><%= link_to page, person_path(@person.id, search:params[:search],type:params[:type],page:page) %></li>
      <% else %>
      <li><%= link_to page, person_path(@person.id, search:params[:search],type:params[:type],page:page) %></li>
      <% end %>
    <% end %>
    <li>
      <% if params[:page].to_i == 5 %>
        <%= link_to '>', person_path(@person.id, search:params[:search],type:params[:type],page:5) %>
      <% else %>
        <%= link_to '>', person_path(@person.id, search:params[:search],type:params[:type],page:params[:page].to_i + 1) %>
      <% end %>
    </li>
  </ul>
</nav>
<% end %>

app/views/persons/_product.html.erb
<% if @products != nil %>
  <div class="row">
     <% @products.each do |product| %>
       <div class="product col-xs-3 thumbnail">
         <% if product['MediumImage'] %>
         <div class='product-img'>
           <%= link_to image_tag(product['MediumImage']['URL']), product['DetailPageURL']  %>
           <% else %>
           <img src="https://placehold.it/160?text=no+image" alt="" />
           <% end %>
         </div>
         <div class="caption">
           <p>
             <%= link_to truncate(product['ItemAttributes']['Title'], length: 50), product['DetailPageURL'] if product['ItemAttributes']['Title'] %>
           </p>
           <h5>
             <%#= link_to product['Offers']['Offer']['OfferListing']['Price']['FormattedPrice'], product['DetailPageURL'] if product['Offers']['Offer'] %>
           </h5>
         </div>
       </div>
     <% end %>
   </div>
<% end %>

app/views/persons/edit.html.erb
<h1>Persons#edit</h1>
<p>Find me in app/views/persons/edit.html.erb</p>

app/views/persons/index.html.erb
<div class='container persons-wrapper'>
  <h4><%= link_to "reminders", reminders_path %> | <%= link_to "history", persons_path %></h4>
  <% @reminders.each do |reminder| %>
    <% if current_user.id == reminder.user_id && reminder.when.change(hour:0) < Time.now.change(hour:0) %>
       <div class= "col-md-6 panel panel-body">
          <h3><%= reminder.person.name.capitalize %></h3>
          <h3><%= reminder.reminder_type.event %> (<%= reminder.when.strftime("%D") %>) <%= link_to 'Renew', reminders_path, class:"btn btn-success btn-sm" %></h3>
          <% reminder.person.interests.each do |interest| %>
          <h4><%= interest.name %></h4>
          <% end %>
       </div>
    <% end %>
  <% end %>
</div>

app/views/persons/new.html.erb
<h1>Persons#new</h1>
<p>Find me in app/views/persons/new.html.erb</p>

app/views/persons/show.html.erb
<div class="container">
  <div class="row text-center panel panel-body">
    <% @person.reminders.each do |reminder| %>
    <h1><%= @person.name.capitalize %>'s <%= reminder.reminder_type.event %> is on <%= reminder.when.strftime("%D") %></h1>
    <% end %>
    <%= render 'interest' %>
  </div>
  <%= render 'pagination' %>
  <%= render 'product' %>

</div>

app/views/reminders/_amazon.html.erb
<div class="container">
  <%= form_tag amazon_api_path, method: "get" do %>
    <div class="form-group row search-wrapper">
      <%= text_field_tag :search, nil, placeholder: 'search', class:'form-control search-bar' %>
      <%= select_tag :type, options_for_select(@category) %>
      <%= submit_tag "Search", class:'btn btn-primary search-btn' %>
    </div>
  <% end %>

<% if @products != nil %>
  <div class="row">
     <% @products.each do |product| %>
       <div class="product col-md-3 thumbnail">
         <% if product['MediumImage'] %>
         <%= link_to image_tag(product['MediumImage']['URL']), product['DetailPageURL']  %>
         <% else %>
         <img src="https://placehold.it/160?text=no+image" alt="" />
         <% end %>
         <div class="caption">
           <p>
             <%= link_to truncate(product['ItemAttributes']['Title']), truncate(product['DetailPageURL']) if product['ItemAttributes']['Title'] %>
           </p>
           <h5>
             <%#= link_to product['Offers']['Offer']['OfferListing']['Price']['FormattedPrice'], product['DetailPageURL'] if product['Offers']['Offer'] %>
           </h5>
         </div>
       </div>
     <% end %>
   </div>
<% end %>
</div>

app/views/reminders/_form.html.erb
<%= form_for @reminder do |r| %>
  <%= fields_for @person do |rp| %>
    <%= fields_for @reminder_type do |rrt| %>
      <div class="form-group">
        <%= rp.label :name, "Name" %>
        <%= rp.text_field :name, class:'form-control' %>
      </div>
      <div class="form-group">
        <%= rrt.label :event, "Event" %>
        <%= rrt.text_field :event, class:'form-control' %>
      </div>
      <div class="form-group">
        <%= r.label :when, "Date" %>
        <%= r.text_field :when, class:'form-control', ampm:true, id:"datetimepicker" %>
      </div>
      <div class="form-group">
        <%= r.label :send_text %>
        <%= r.check_box :send_text %>
        <%= r.label :send_email %>
        <%= r.check_box :send_email %>
      </div>
      <div class="form-group">
        <%= r.submit class:'btn btn-primary' %>
      </div>
    <% end %>
  <% end %>
<% end %>

<script type="text/javascript">
// jQuery('#datetimepicker').datetimepicker();
jQuery('#datetimepicker').datetimepicker({
 timepicker:false,
 format:'d.m.Y'
});
</script>

app/views/reminders/amazon_api.html.erb
<div class="container">
  <%= form_tag amazon_api_path, method: "get" do %>
    <div class="form-group row search-wrapper">
      <%= text_field_tag :search, nil, placeholder: 'search', class:'form-control search-bar' %>
      <%= select_tag :type, options_for_select(@category) %>
      <%= submit_tag "Search", class:'btn btn-primary search-btn' %>
    </div>
  <% end %>

<% if @products != nil %>
  <div class="row">
     <% @products.each do |product| %>
       <div class="product col-md-3 thumbnail">
         <% if product['MediumImage'] %>
         <%= link_to image_tag(product['MediumImage']['URL']), product['DetailPageURL']  %>
         <% else %>
         <img src="https://placehold.it/160?text=no+image" alt="" />
         <% end %>
         <div class="caption">
           <p>
             <%= link_to truncate(product['ItemAttributes']['Title']), truncate(product['DetailPageURL']) if product['ItemAttributes']['Title'] %>
           </p>
           <h5>
             <%#= link_to product['Offers']['Offer']['OfferListing']['Price']['FormattedPrice'], product['DetailPageURL'] if product['Offers']['Offer'] %>
           </h5>
         </div>
         <h4>

         </h4>
       </div>
     <% end %>
   </div>
<% end %>
</div>

app/views/reminders/edit.html.erb
<h1>Reminders#edit</h1>
<p>Find me in app/views/reminders/edit.html.erb</p>

app/views/reminders/etsy_api.html.erb
div class="container">
<%= form_tag etsy_api_path, method: "get" do %>
    <%= text_field_tag :search, nil, placeholder: 'search' %>
    <%= submit_tag "Search" %>
<% end %>

<% if @products != nil %>
<h1>Products from the Etsy API</h1>
     <% @products.each do |product| %>
       <div class="product col-md-3 itembox">
         <%= link_to image_tag(product['MediumImage']['URL']), product['DetailPageURL'] if product['MediumImage'] %>
         <br>
         <%= link_to product['ItemAttributes']['Title'], product['DetailPageURL'] if product['ItemAttributes']['Title'] %>
         <br>
         <%= link_to product['Offers']['Offer']['OfferListing']['Price']['FormattedPrice'], product['DetailPageURL'] if product['Offers']['Offer'] %>
         <br>
       </div>

     <% end %>
<% end %>
</div>

app/views/reminders/index.html.erb
<div class="container reminder-wrapper">
  <h4><%= link_to "reminders", reminders_path %> | <%= link_to "history", persons_path %></h4>
<% @reminders.each do |reminder| %>
    <% if current_user.id == reminder.user_id && reminder.when.change(hour:0) >= Time.now.change(hour:0) %>
      <div class="panel panel-body col-sm-6 single-reminder">
        <h3 class="reminder-text">
          <%= link_to reminder.person.name.capitalize + " has a " + reminder.reminder_type.event + " on " + reminder.when.strftime("%D"), person_path(reminder.person.id) %>
          <span class="delete"><%= link_to "x", reminder_path(reminder.id), method: :delete, data:{confirm:"are you sure?"}, class:"btn btn-danger btn-xs" %></span>
        </h3>
      </div>
  <% end %>
<% end %>

<!-- modal  -->

  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Create a Reminder</h4>
        </div>
        <div class="modal-body">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <button type="button" class="btn btn-primary col-xs-12 btn-lg" data-toggle="modal" data-target="#myModal">
      New Reminder
    </button>
  </div>
</div>

app/views/reminders/new.html.erb
<h1>New Form</h1> 
<%= render 'form' %>

app/views/users/edit.html.erb
<div class="">
<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :phone %>
    <%= f.text_field :phone, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit class:'btn btn-default' %>
  </div>
<% end %>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6">
            <div class="well well-sm">
                <div class="row">
                    <div class="col-sm-6 col-md-4">
                        <%= image_tag @user.image_url %>
                    </div>
                    <div class="col-sm-6 col-md-8">
                        <h4><%= @user.name %></h4>
                        <p>
                            <i class="glyphicon glyphicon-envelope"></i>Email: <%= @user.email %>
                            <br />
                            <i class="glyphicon glyphicon-phone"></i>Phone: <%= @user.phone %>
                            <br />
                            <i class="glyphicon glyphicon-globe"></i><%= link_to "Edit", edit_user_path(current_user.id) %>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>